<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $fatecs = [
            'Fatec Araçatuba - Prof. Fernando Amaral de Almeida Prado',
            'Fatec Praia Grande',
            'Fatec Baixada Santista - Rubens Lara',
            'Fatec Bebedouro - Jorge Caram Sabbag',
            'Fatec Barretos',
            'Fatec Bauru',
            'Fatec Jahu',
            'Fatec Lins - Prof. Antonio Seabra',
            'Fatec Americana - Ministro Ralph Biasi',
            'Fatec Araras - Antonio Brambilla',
            'Fatec Bragança Paulista - Jornalista Omair Fagundes de Oliveira',
            'Fatec Campinas',
            'Fatec Indaiatuba - Dr. Archimedes Lammoglia',
            'Fatec Itapira - Ogari de Castro Pacheco',
            'Fatec Itatiba - Maria Eunice Amadeo de Almeida',
            'Fatec Jundiaí - Deputado Ary Fossen',
            'Fatec Mococa',
            'Fatec Mogi Mirim - Arthur de Azevedo',
            'Fatec Piracicaba - Deputado Roque Trevisan',
            'Fatec Sumaré',
            'Fatec Araraquara - Prof. José Arana Varela',
            'Fatec Matão - Luiz Marchesan',
            'Fatec São Carlos',
            'Fatec Taquaritinga',
            'Fatec Franca - Dr. Thomaz Novelino',
            'Fatec Capão Bonito',
            'Fatec Assis',
            'Fatec Garça - Deputado Julio Julinho Marcondes de Moura',
            'Fatec Marília - Estudante Rafael Almeida Camarinha',
            'Fatec Ourinhos',
            'Fatec Pompeia - Shunji Nishimura',
            'Fatec Barueri - Padre Danilo José de Oliveira Ohl',
            'Fatec Carapicuíba',
            'Fatec Cotia',
            'Fatec Diadema - Luigi Papaiz',
            'Fatec Ferraz de Vasconcelos — Ferraz de Vasconcelos',
            'Fatec Franco da Rocha - Giuliano Cecchettini',
            'Fatec Guarulhos',
            'Fatec Itaquaquecetuba',
            'Fatec Mauá',
            'Fatec Mogi das Cruzes',
            'Fatec Osasco - Prefeito Hirant Sanazar',
            'Fatec Santana de Parnaíba',
            'Fatec Santo André',
            'Fatec São Bernardo do Campo - Adib Moisés Dib',
            'Fatec São Caetano do Sul - Antonio Russo',
            'Fatec Ipiranga - Pastor Enéas Tognini',
            'Fatec Itaquera - Prof. Miguel Reale',
            'Fatec São Paulo',
            'Fatec Sebrae',
            'Fatec Tatuapé - Victor Civita',
            'Fatec Zona Leste',
            'Fatec Zona Sul - Dom Paulo Evaristo Arns',
            'Fatec Adamantina',
            'Fatec Presidente Prudente',
            'Fatec Registro',
            'Fatec Jaboticabal - Nilo de Stéfani',
            'Fatec Ribeirão Preto',
            'Fatec Sertãozinho - Deputado Waldyr Alceu Trigo',
            'Fatec Catanduva',
            'Fatec Jales - Professor José Camargo',
            'Fatec São José do Rio Preto',
            'Fatec Cruzeiro - Prof. Waldomiro May',
            'Fatec Guaratinguetá - Prof. João Mod',
            'Fatec Jacareí - Professor Francisco de Moura',
            'Fatec Pindamonhangaba',
            'Fatec São José dos Campos - Prof. Jessen Vidal',
            'Fatec São Sebastião - São Sebastião',
            'Fatec Taubaté',
            'Fatec Botucatu',
            'Fatec Itapetininga - Prof. Antonio Belizandro Barbosa Rezende',
            'Fatec Itu - Dom Amaury Castanho',
            'Fatec de São Roque',
            'Fatec Sorocaba - José Crespo Gonzales',
            'Fatec Tatuí - Prof. Wilson Roberto Ribeiro de Camargo',
        ];

        foreach($fatecs as $fatec) {
            DB::table('colleges')->insert([
                'title' => $fatec,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $courses = [
            'Agroindústria',
            'Agronegócio',
            'Alimentos',
            'Análise de Processos Agroindustriais',
            'Análise e Desenvolvimento de Sistemas',
            'Automação e Manufatura Digital',
            'Automação Industrial',
            'Banco de Dados',
            'Big Data no Agronegócio',
            'Big Data para Negócios',
            'Biocombustíveis',
            'Ciência de Dados',
            'Comércio Exterior',
            'Construção Civil - Edifícios',
            'Construção de Edifícios',
            'Construção Naval',
            'Controle de Obras',
            'Cosméticos',
            'Defesa Cibernética',
            'Desenvolvimento de Produtos Plásticos',
            'Desenvolvimento de Software Multiplataforma',
            'Design de Mídias Digitais',
            'Design de Moda',
            'Design de Produto com ênfase em Processos de Produção e Industrialização',
            'Eletrônica Automotiva',
            'Eletrônica Industrial',
            'Estradas',
            'Eventos',
            'Fabricação Mecânica',
            'Geoprocessamento',
            'Gestão Ambiental',
            'Gestão Comercial',
            'Gestão da Produção Industrial',
            'Gestão da Qualidade',
            'Gestão da Tecnologia da Informação',
            'Gestão de Energia e Eficiência Energética',
            'Gestão de Negócios e Inovação',
            'Gestão de Recursos Humanos',
            'Gestão de Serviços',
            'Gestão de Turismo',
            'Gestão Empresarial',
            'Gestão Financeira',
            'Gestão Hospitalar',
            'Gestão Portuária',
            'Hidráulica e Saneamento Ambiental',
            'Informática para Negócios',
            'Instalações Elétricas',
            'Jogos Digitais',
            'Logística',
            'Logística Aeroportuária',
            'Manufatura Avançada',
            'Manutenção de Aeronaves',
            'Manutenção Industrial',
            'Marketing',
            'Materiais',
            'Mecânica - Modalidade Projetos',
            'Mecânica - Processos de Produção',
            'Mecânica Automobilística',
            'Mecânica de Precisão',
            'Mecânica: Processos de Soldagem',
            'Mecanização em Agricultura de Precisão',
            'Mecatrônica Industrial',
            'Meio Ambiente e Recursos Hídricos',
            'Microeletrônica',
            'Polímeros',
            'Processos Metalúrgicos',
            'Processos Químicos',
            'Produção Agropecuária',
            'Produção Fonográfica',
            'Produção Industrial',
            'Produção Têxtil',
            'Projetos de Estruturas Aeronáuticas',
            'Projetos Mecânicos',
            'Radiologia',
            'Redes de computadores',
            'Refrigeração, Ventilação e Ar Condicionado',
            'Secretariado',
            'Secretariado e Assessoria Internacional',
            'Segurança da Informação',
            'Silvicultura',
            'Sistemas Biomédicos',
            'Sistemas Embarcados',
            'Sistemas Navais',
            'Sistemas para Internet',
            'Soldagem',
            'Transporte Terrestre',
        ];

        foreach($courses as $course) {
            DB::table('courses')->insert([
                'title' => $course,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $subjects = [
            'ARQUITETURA E ORG DE COMP',
            'INGLÊS I',
            'INGLÊS II',
            'INGLÊS III',
            'INGLÊS IV',
            'INGLÊS V',
            'INGLÊS VI',
            'ALG E LOG PROG',
            'PROG MICROINF',
            'MATEMÁTICA DISCRETA',
            'COMUNICAÇÃO E EXPRESSÃO',
            'SISTEMAS DE INFORMAÇÃO',
            'ADMINISTRAÇÃO',
            'CÁLCULO',
            'ESTATÍSTICA APLICADA',
            'ENGENHARIA DE SOFTWARE I',
            'ENGENHARIA DE SOFTWARE II',
            'ENGENHARIA DE SOFTWARE III',
            'CONTABILIDADE',
            'SISTEMAS OPERACIONAIS I',
            'SISTEMAS OPERACIONAIS II',
            'ELITIVA PHP',
            'LAB. DE HARDWARE',
            'LINGUAGEM DE PROGRAMAÇÃO',
            'ELETIVA - LP III - JAVA',
            'BANCO DE DADOS',
            'INTERAÇ. HUM. COMP.',
            'PROG. LINEAR E APLICAÇÕES ',
            'ESTRUTURA DE DADOS',
            'ECONOMIA E FIN.',
            'SOCIEDADE E TEC.',
            'REDES DE COMP',
            'GESTÃO DE PROJETOS',
            'PROG ORIENT OBJ',
            'LAB BANCO DE DADOS',
            'SEGURANÇA DA INFORMAÇÃO',
            'MET. DA PESQ. CIENT.- TECNOL',
            'LAB. DE ENG. DE SOFTWARE',
            'TÓP. ESPECIAIS INFORMÁTICA',
            'EMPREENDEDORISMO',
            'GESTÃO DE EQUIPES',
            'ÉTICA E RESPONS. PROFISSIONAL',
            'GESTÃO DE T. INFORMÁTICA',
            'INTELIGÊNCIA ARTIFICIAL',
            'ELETIVA II PROG. WEB',
            'ELETIVA - PROG. DISPOSIT. MÓVEIS',
        ];

        foreach($subjects as $subject) {
            DB::table('subjects')->insert([
                'title' => $subject,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::table('students')->insert([
            'college_id' => 41,
            'name' => 'Gabriel Leite',
            'email' => 'gabriel.leite7@fatec.sp.gov.br',
            'password' => Hash::make('12345678'),
            'email_verified_at' => now(),
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('students')->insert([
            'college_id' => 41,
            'name' => 'Mateus Ivanhes de Paula',
            'email' => 'mateus@fatec.sp.gov.br',
            'password' => Hash::make('12345678'),
            'email_verified_at' => now(),
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
